// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBirhBQ-VQFaAUAFnYjzm2UDPer2xlf3Eo',
    appId: '1:1012336958631:web:41748c96e2f097546f4f82',
    messagingSenderId: '1012336958631',
    projectId: 'health-connect-1171f',
    authDomain: 'health-connect-1171f.firebaseapp.com',
    storageBucket: 'health-connect-1171f.firebasestorage.app',
    measurementId: 'G-W9CVLC7VN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYkt2zhSFWw8BSZ5j2mke9u-Qw1i2Byb8',
    appId: '1:1012336958631:android:c723bb62f41813ad6f4f82',
    messagingSenderId: '1012336958631',
    projectId: 'health-connect-1171f',
    storageBucket: 'health-connect-1171f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZzRN68Hk-o2CP0tLbHT1z_RSGxMGKq5M',
    appId: '1:1012336958631:ios:66283b59987932946f4f82',
    messagingSenderId: '1012336958631',
    projectId: 'health-connect-1171f',
    storageBucket: 'health-connect-1171f.firebasestorage.app',
    iosBundleId: 'com.example.healthConnect',
  );
}
